# Generated by Django 4.2.2 on 2023-06-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('id', 'username'), 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='django_app_profile_model_table',
        ),
    ]
