# Generated by Django 4.2.2 on 2023-06-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_alter_profile_options_rename_name_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
