# Generated by Django 4.2.2 on 2023-06-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
