# Generated by Django 4.2.2 on 2023-06-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_postcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
