# Generated by Django 4.2.2 on 2023-06-28 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0011_profilecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilecomment',
            options={'ordering': ('-created',), 'verbose_name': 'Отзыв к профилю', 'verbose_name_plural': 'Отзывы к профилю'},
        ),
        migrations.AlterField(
            model_name='profilecomment',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, help_text='<small class="text-muted">ForeignKey</small><hr><br>', null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_app.profile', verbose_name='Профиль'),
        ),
    ]
