# Generated by Django 4.2.2 on 2023-06-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0014_alter_complaint_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/ads/%Y/%m/%d/'),
        ),
    ]
